### PR TITLE
WIP: try to implement customInteraction zoom in/out

### PR DESCRIPTION
**Pull request by breznak**
model from http://dygraphs.com/gallery/#g/interaction
but failing..

### CODE REVIEW

**Comment by breznak** [comment]
@jefffohl (a low priority) but I was trying to get the zoom out working, copied the example but the code fails as the `downV3` etc are not defined. Is the problem obvious to you?

**Comment by jefffohl** [comment]
I will take a look at it, and if I can get it working, I will submit a new PR.

**Comment by jefffohl** [comment]
@breznak - my understanding is that you like the default zoom method - but you would like to enable a zoom-out that is operated by the mouse scroll wheel, when the cursor is over the graph. Is this correct?

**Comment by breznak** [comment]
@jefffohl which zoom do you find the most suitable? I like the current "mouse zoom" in `plot_results`, but testing on the new CSV I've just realized 1 annoying thing - you cannot zoom in and then use the mouse to click+drag to move the graph (or can you?). On the method in this PR I like that you can zoom in/out (eg. (ctrl+)dbl click) and drag the graph.

**Comment by jefffohl** [comment]
@breznak With the default zoom, you can pan left and right on a zoomed-in view by holding the "alt" key while clicking and moving the mouse.

**Comment by jefffohl** [comment]
@breznak - I prefer the default zoom (with the animated zoom), personally. I can see room for possibly allowing the user to gradually zoom out, instead of jumping all the way out, but I don't find it too inconvenient the way that it is now.

**Comment by breznak** [comment]
@jefffohl thanks for the notice about `alt` - if it worked I would be very satisfied with the default zoom too (the gradual zoom out is a minor), unfortunately it seems it does not work here (FF,Chrome, Ubuntu, KDE) :disappointed: typically alt + mouse drag on Linux moves the whole window.

**Comment by jefffohl** [comment]
@breznak On Linux, hold the `SHIFT` key instead of the `ALT` key.

**Comment by breznak** [comment]
@jefffohl damn I'm stupid! :D works beautifully (and that I have tried all the other keys - ctrl, fn, command, R-alt, .. :) )
Closing this PR as not-needed. But I should write a doc paragraph how to use the graph instead.

**Pull request closed without merging**
