### PR TITLE
Plot results options

### PR DESCRIPTION
**Pull request by breznak**
I've gone through the graph options, 
questionable is the "highlighted series", 
wonder if the `labelsDiv` can be useful? 

CC @jefffohl

### CODE REVIEW

**Comment by jefffohl** [comment]
Thanks @breznak. My thoughts:

* We don't need the title. We are already showing the file name above the graph.
* I don't think we want to use UTC time. This is actually modifying the timestamp. See here: http://dygraphs.com/tests/labelsDateUTC.html
*  I think there is also an argument to be made for just leaving them blank, as these labels should be intuitive anyway. But if you feel the need for them, I think we could simplify them to just say, "Values" for the y-axis, and "Time" for the x-axis
* The highlighted series is kind of neat - but it depends on how many series are shown. If there are a lot, it is kind of confusing. Just a few, and it works well. I would say, leave it in.
* The `labelsDiv` we don't need, as that display is already handled in the fields rendering to the right of the graph.

**Comment by breznak** [comment]
Thanks for review @jefffohl , I agree on the rest and will modify accordingly, just wanna discuss these: 
- title, `labelsDiv` - I know it is already solved, just saying if the code would be simpler if we delegate that to DyGraph? 
- UTC: I'm still thinking UTC is better as it's the same series for everyone - esp. for world-wide community like us, if we wanted to discuss "the anomaly at 11pm ...", take the linked example, for me the top/local graph starts at 20:00, I'm sure yours is different, right?

**Comment by breznak** [comment]
@ labels: I agree they are quite self explanatory, on the other hand some academics are too rigid for graphs without labels :smiling_imp: (and this tool will be useful generator of screenshots), so I'd go with the simplified labels (?)

**Comment by jefffohl** [comment]
Further thoughts:
* Regarding `labelsDiv` - Yes, the code will be slightly more simple, but it will not look as nice. I don't see a benefit here.
* Regarding labels. If you feel the typical user will require them, then minimal labels sound fine.
* Regarding UTC. I must say I strongly disagree here. The tool has no idea what the intent of the user is here. This may be historical data where the local time is very important. In the hotgym example, users may notice that the temperature goes up at a certain time - perhaps that is when the building is no longer in shadow (at say, 10AM in the morning) - and this will be misleading if we are mysteriously changing the timestamp to UTC - so that the timestamp is 10 hours off. If the user wants to convert to UTC, that should be up to them. That said, if you think the option is important, we could add a toggle that converts the timestamps to UTC.

**Comment by breznak** [comment]
@jefffohl 
About UTC, luckily we can put this problem off, as DyGraphs don't support the datestring with TZ info :wink: 

> You can manually verify this using a JavaScript console. If a value doesn't parse, dygraphs will put a warning about it on your console. But beware: different browsers support different date formats!
Here are some valid date formats:
2009-07-12
2009/07/12
2009/07/12 12
2009/07/12 12:34
2009/07/12 12:34:56

Our testing on hotgym was pointless as it does not contain the TZ info, I've created a CSV file to test this ~~~(maybe will commit it(?), but it's not parsable)~~~, I'll revert the `labelsUTC`. And that I think is all for this PR, we've agreed on the rest, right? 

PS: irrelevant note about the UTC/local - neither is 100% "good": 
if you record a temperature increase in the morning at 8:00am GMT-8, with `local` I'll see the increase at (+10) 6pm GMT+2, you'll see it yourself correctly at 8am GMT-8. So local works fine for "your own files", but will fail for "shared files" (which I thought would happen in the NuPIC community). 
If we both open it with `UTC`, we'll see the increase at 4pm GMT. Is in above, this would be better for "world-wide communication".

**Comment by breznak** [comment]
@jefffohl I think we've agreed on all points after the changes on your last review, so I'll merge. Please let me know if there's something more you'd add. This boiled down to only the `highlightSeries` change (which I'm not even 100% sure about if it's useful - but let's see).

**Comment by breznak** [comment]
merged to https://github.com/numenta/nupic/issues/2658

**Comment by jefffohl** [comment]
Sounds good @breznak. By the way, we have set our app up in such a way that DyGraphs is not handling the conversion of timestamp strings into dates. We are doing this before we send the data to DyGraph as a Javascript array - where the time element is either a Number or a Date object.

**Comment by breznak** [comment]
> DyGraphs is not handling the conversion of timestamp strings into dates

@jefffohl ha, good catch!

**Pull request merged**
